.TH INDICATOR-XKBMOD 1
.SH NAME
indicator-xkbmod \- simple Ubuntu keyboard modifiers indicator
.SH SYNOPSIS
.B indicator-xkbmod
[\fB\-l\fR]
[\fB\-\-use\-label\fR]
.SH DESCRIPTION
.B indicator-xkbmod
simple Ubuntu keyboard modifiers indicator.
.SH OPTIONS
.TP
.BR \-l ", " \-\-use-label 
Use indicator label instead of icon to show the state.
